version: "3.5"
volumes:
  dc1_etc: {}
  dc1_private: {}
  dc1_var: {}
services:
  dc1:
    image: diegogslomp/samba-ad-dc
    restart: unless-stopped
    network_mode: host
    container_name: dc1
    hostname: DC1
    privileged: true
    environment:
      REALM: TEST.LOCAL
      DOMAIN: TEST
      ADMIN_PASS: Passw0rd
      DNS_FORWARDER: 8.8.8.8
    volumes:
      - dc1_etc:/usr/local/samba/etc
      - dc1_private:/usr/local/samba/private
      - dc1_var:/usr/local/samba/var

  samba-ad-api:
    image: samba-ad-api:test
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: samba-ad-api
    environment:
      - SAMBA_HOST=ldap://localhost:389
      - SECRET_KEY=jnkosdfjghsdjhlksjdmhlnsdtuyrtuye32766565235y329
      - SECRET_SALT=2310hjklsm124537
      - ACCESS_TOKEN_EXPIRE_SECONDS=60000
    ports:
      - 8000:8000
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    privileged: true
    restart: unless-stopped
    network_mode: host
